Initial pr
briefmnews/briefme-subscription pull request #1
Opened 2020-05-11 14:56 UTC by ThomSawyer

2020-06-23 14:07 UTC, cirotix requested changes

2020-06-23 14:07 UTC, cirotix commented on requirements.txt
> +Django==2.2.12
Wouldn't it be better to have something less restricted such as:
```
Django>=2.2,<2.3
```
(It could be even larger).

And actually as we have a `setup.py` do we really need a `requirements.txt`?

2020-06-23 14:07 UTC, cirotix commented on briefme_subscription/models.py
> +    classes instead of strictly following Chargify's logic.
This can be removed.

2020-06-23 14:07 UTC, cirotix commented on briefme_subscription/models.py
> +            chargify_subscription or self.chargify_helper.get_subscription(self.uuid)
It probably should not be done here (as it is a refacto):
but we could have:
```python
self.chargify_subscription_cache = (
            chargify_subscription or self.chargify_helper.get_subscription(self.uuid) or {}
)
```

2020-06-29 16:07 UTC, ThomSawyer commented on briefme_subscription/models.py
> +            chargify_subscription or self.chargify_helper.get_subscription(self.uuid)
What do you mean by "It should not be done here" ?
I'm not sure I understand what to do with this method.

2020-06-29 16:13 UTC, ThomSawyer commented on briefme_subscription/models.py
> +    classes instead of strictly following Chargify's logic.
Yes thank you : 315d260

2020-06-29 16:14 UTC, ThomSawyer commented on requirements.txt
> +Django==2.2.12
You are right : 1c68886

We do need a requirements file for the tests in our local devices and in the CI

2020-06-29 16:14 UTC, ThomSawyer commented on briefme_subscription/models.py
> +            chargify_subscription or self.chargify_helper.get_subscription(self.uuid)
I added the empty dict fallback in cca2baa

2020-07-06 09:18 UTC, merged